### ISSUE TITLE
Possible to include draft API?

### ISSUE THREAD

**Issue by mschubert** [rwinlib/zeromq#1]
Would it be possible to include the ZeroMQ draft API in the Windows libzmq build?

The reason I'm asking is because functionality like `ZMQ_ROUTER_NOTIFY` are only available as draft (since 2018), and this is the only way to detect which worker connected/disconnected on a `ROUTER` socket.

**Comment by jeroen** [comment]
I justed updated it to the latest zeromq. Does that include the draft api?

**Comment by mschubert** [comment]
You'd need to explicitly compile with `-DENABLE_DRAFTS=ON` (`./configure --enable-drafts`).

Sorry for my bad timing, I wanted to ask this for a while and just saw that you updated.

**Comment by jeroen** [comment]
OK I'll try to rebuild zeromq with `--enable-drafts`

**Comment by jeroen** [comment]
OK I am now rebuilding with `--enable-drafts` however according to the autoconf documentation this is actually the default? So perhaps all that is needed is to set a CPPFLAG in the rzmq `Makevars.win`?

**Comment by jeroen** [comment]
Based on the code below I guess you need to add `-DZMQ_BUILD_DRAFT_API` to the `PKG_CPPFLAGS` in `Makevars.win` to make these APIs available:

https://github.com/rwinlib/zeromq/blob/34bc4474dca7f7bd4f5f05e8b797e2109937dbcb/include/zmq.h#L652-L779

**Comment by mschubert** [comment]
Ok, I guess it's enabled if you're building in a git repostory ([`configure.ac#L981-L983`](https://github.com/zeromq/libzmq/blob/master/configure.ac#L981-L983)).

```autoconf
if test "x$cross_compiling" = "xyes"; then
    #   Enable draft by default when cross-compiling
    defaultval=yes
else
    # enable draft API by default if we're in a git repository
    # else disable it by default; then allow --enable-drafts=yes/no override
    AC_CHECK_FILE($srcdir/.git, [defaultval=yes], [defaultval=no])
fi
```

Thanks for looking into it!
